feat(util): bbcode
bangumi/frontend pull request #100
Opened 2022-06-18 10:41 UTC by 22earth

2022-06-18 10:55 UTC, Trim21 commented on packages/utils/bbcode/__test__/convert.test.ts
> +      '<img src="/img/smiles/tv/15.gif" smileid="54" alt="(bgm38)" />',
用cdn的表情图片 https://lain.bgm.tv/img/smiles/tv/05.gif

2022-06-18 14:32 UTC, Ayase-252 commented on packages/utils/bbcode/__test__/convert.test.ts
> +    const nodes: CodeNodeTypes[] = [
可以用 `[[input, expected], ...]` 这样的方式来写用例。分成两个数组感觉不太直观。下同。

2022-06-18 15:58 UTC, Trim21 commented on packages/utils/bbcode/__test__/convert.test.ts
> +    for (let i = 0; i < tests.length; i++) {
```
    for (const [raw,expected] of tests) {
```

2022-06-18 16:34 UTC, Ayase-252 requested changes
不符合标准的 tag 可能需要处理下，request change 下防止意外合入。

2022-06-18 16:34 UTC, Ayase-252 commented on packages/utils/bbcode/parser.ts
> +  parseNodes (): CodeNodeTypes[] {
感觉 `parseNodes` 改成 `parse(input: string)` 比较好。现在 `parseNodes` 感觉和 `parseNode` 有点相像，乍一看不知道怎么用这个类。

2022-06-18 16:34 UTC, Ayase-252 commented on packages/utils/bbcode/parser.ts
> +  parseNodes (): CodeNodeTypes[] {
其他没必要暴露的解析方法也可以设置成 private 的

2022-06-18 16:34 UTC, Ayase-252 commented on packages/utils/bbcode/parser.ts
> +  private pos: number
实在要用 `private` 的话，倾向于 `#private` 语法吧。毕竟标准化了（虽然很难看

Ref: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields

2022-06-18 16:53 UTC, cokemine commented on packages/utils/bbcode/parser.ts
> +  private pos: number
现在的 Vite 配置会转义这个语法吗。Private class methods 要 Chrome 84+ 或 Firefox 90+ 了。太超前了

2022-06-18 17:16 UTC, Trim21 commented on packages/utils/bbcode/parser.ts
> +  private pos: number
没有browserlist吗？

2022-06-18 17:27 UTC, cokemine commented on packages/utils/bbcode/parser.ts
> +  private pos: number
Vite 默认 target 是原生支持 es module，那照它说的的话期待的行为应该是会转义这个语法，不过性能可能不会很好。
https://esbuild.github.io/content-types/#private-member-performance
感觉 TS 的编译时检查足够了（

2022-06-18 17:35 UTC, Ayase-252 commented on packages/utils/bbcode/parser.ts
> +  private pos: number
那用 ts 的 `private` 修饰符也行（

2022-06-18 17:35 UTC, Ayase-252 commented on packages/utils/bbcode/parser.ts
> +  private pos: number
那用 ts 的 `private` 修饰符也行（

2022-06-19 02:23 UTC, 22earth commented
> 不符合标准的 tag 可能需要处理下，request change 下防止意外合入。

额，这个问题没有理解到。
现在解析器能够传入自定义校验规则

2022-06-19 03:37 UTC, Ayase-252 commented
哦，是不符合标准的 bbcode

2022-06-19 04:42 UTC, 22earth commented
> 哦，是不符合标准的 bbcode

`[b]加粗[/s]`  `[unknown][/unknown]`   都会解析成字符串。
 `[b][/b]` 内部没有内容也解析成字符串。

```javascript
  test('custom bbcode', () => {
    const input = '[mybbcode]测试自定义tag[/mybbcode]'
    const nodes = new Parser(input, ['mybbcode']).parse()
    expect(nodes).toEqual([{
      type: 'mybbcode',
      children: ['测试自定义tag']
    }])
  })
```
传入解析器的自定义 `tag` 会被解析

2022-06-19 07:39 UTC, Ayase-252 commented on packages/utils/bbcode/__test__/parser.test.ts
> +    // expect(getNodes(input)).toEqual(expect.arrayContaining(tests));
这些注释还需要吗？如果不需要的话可以删掉。

2022-06-19 07:40 UTC, Ayase-252 commented on packages/utils/bbcode/__test__/parser.test.ts
> +  test('bold bbcode', () => {
这些测试如果有必要测试的话，可以单列出来成为测试用例，下同

2022-06-19 07:58 UTC, Ayase-252 commented on packages/utils/bbcode/parser.ts
> +  // 解析 (bgm38) (bgm1)
这个注释有点迷惑性，这个方法好像也处理了 emoji 文字。

2022-06-19 08:02 UTC, Ayase-252 commented on packages/utils/bbcode/parser.ts
> +      // 1-16号表情最长为7
可以注明下是哪个表情最长？

2022-06-19 08:03 UTC, Ayase-252 commented on packages/utils/bbcode/parser.ts
> +      const target = this.input.slice(this.pos, this.pos + 8)
8 可以换成常量 `MAX_EMOJI_LENGTH`

2022-06-19 08:31 UTC, Ayase-252 commented on packages/utils/bbcode/parser.ts
> +    this.pos += 4
可以注释下是为了跳过 `(bgm`

2022-06-19 08:31 UTC, Ayase-252 commented on packages/utils/bbcode/parser.ts
> +    if (openTag === 'code') {
可以注释下，`code` 需要尽可能长的匹配。

2022-06-19 08:31 UTC, Ayase-252 commented on packages/utils/bbcode/parser.ts
> +      this.pos = idx + 7
`[/code]` 弄成一个常量吧，这里 `7` 可以用常量 `.length` 替代

2022-06-19 08:31 UTC, Ayase-252 commented on packages/utils/bbcode/parser.ts
> +    // 正则的方式暂时没用到 注释了
如果这个 commit 不会使用的话，注释可以删了。如果有后续计划的话可以写个 `TODO` 注释

2022-06-19 08:31 UTC, Ayase-252 commented on packages/utils/bbcode/parser.ts
> +    if (openTag === 'code') {
可能也需要加一个 `[code][/code][/code]` 的测试用例

2022-06-19 08:33 UTC, Trim21 commented on packages/utils/bbcode/parser.ts
> +    if (openTag === 'code') {
`[code]1[/code][/code] [code]2[/code]`（

2022-06-19 09:03 UTC, 22earth commented on packages/utils/bbcode/__test__/parser.test.ts
> +  test('bold bbcode', () => {
这个测试和下面重复了。已删除。

2022-06-19 09:36 UTC, Trim21 commented
`[code]1[/code][/code] [code]2[/code]` 这个应该转换成`<code><pre>1[/code]</pre></code> <code><pre>2</pre></code>`吧？

2022-06-19 09:44 UTC, Ayase-252 commented
这个有歧义吧...旧站是咋实现的？有测试用的小组吗。

2022-06-19 09:46 UTC, Trim21 commented
> 这个有歧义吧...旧站是咋实现的？有测试用的小组吗。

自己发篇日志就能测试了。

这个我感觉没有歧义吧，`[code]`只匹配下一次`[code]`出现前的最后一个关闭标签。

2022-06-19 09:57 UTC, Ayase-252 commented
![Screen Shot 2022-06-19 at 17 56 55](https://user-images.githubusercontent.com/6264033/174475619-5b4af5e4-681e-42cd-9c2d-e0c3585d9ad5.png)

绝了，旧站是就近匹配

2022-06-19 10:00 UTC, Trim21 commented
我感觉这个不用跟旧站行为一致...

2022-06-19 10:20 UTC, Ayase-252 commented
那行

2022-06-19 10:30 UTC, Trim21 commented
不过感觉直接最短匹配也可以...

2022-06-19 10:35 UTC, Trim21 commented
大概这样
```
[code]3[/code] [code][code]1[/code][/code] [code]2[/code]

<code><pre>3</pre></code> <code><pre>[code]1[/code]</pre></code> <code><pre>2</pre></code>


[code]3[/code] [code]1[/code][/code] [code]2[/code]

<code><pre>3</pre></code> <code><pre>1[/code]</pre></code> <code><pre>2</pre></code>


[code]3[/code] [code][code]1[/code] [code]2[/code]

<code><pre>3</pre></code> <code><pre>[code]1</pre></code> <code><pre>2</pre></code>
```

2022-06-19 11:16 UTC, 22earth commented
bbcode 的 `[code]`  对应的 `html pre` 吧。为何还在外层包裹   `<code>`
另外这个规则感觉搞复杂了。 还不如就按照旧站的方式来。 
想在  `[code]  xxxx [/code]` 里面输入  `[/code]` 这个需求就很少。实在是想输入可以在里面加空格  `[/co de]`

2022-06-19 11:26 UTC, Trim21 commented
我是想用html的tag表示一下bbcode的解析规则，倒不是真的要转成一模一样的

2022-06-19 12:19 UTC, Trim21 commented
按旧的直接匹配最短的也行。

2022-06-20 15:42 UTC, Ayase-252 reviewed
基本没啥问题了

2022-06-20 15:42 UTC, Ayase-252 commented on packages/utils/bbcode/convert.ts
> +    img = `<img src="${STICKER_DOMAIN_URL}/img/smiles/${id}.gif" smileid="${id}" alt="${stickerId}" />`
直接 return 吧，中间变量 `img` 好像不太必要

2022-06-20 15:42 UTC, Ayase-252 commented on packages/utils/bbcode/parser.ts
> +export const BBCODE_REGEXP = /^\[([a-z]+)(=.+?)?\](.+?)\[\/([a-z]+)\]/
好像除了测试，没有其他地方用到，可以考虑不 export

2022-06-21 04:01 UTC, 22earth commented on packages/utils/bbcode/convert.ts
> +    img = `<img src="${STICKER_DOMAIN_URL}/img/smiles/${id}.gif" smileid="${id}" alt="${stickerId}" />`
已改成 return;
差不不大。个人习惯返回值设置一个变量。最后 `return xx`; 避免忘记了。细想一下 ts 能检测返回值，这是我以前写 js 的习惯。

2022-06-21 04:02 UTC, 22earth commented on packages/utils/bbcode/parser.ts
> +export const BBCODE_REGEXP = /^\[([a-z]+)(=.+?)?\](.+?)\[\/([a-z]+)\]/
移除正则了。这个在替换 html 字符串的时候，可能有用。现在暂时用不上。

2022-06-21 04:05 UTC, 22earth commented
目前不支持  bbcode  `[list]`。我测试了一下旧站的 `[list]` ，基本也是残废功能。
还有 `@user` 这种方式。我推荐采取输入的时候，用户选择下拉时，把输入替换成  `[user]sai[/user]` 或者  `[user=1]sai[/user]`。
或者在生成 html 字符串后，进行统一替换处理。

2022-06-21 07:17 UTC, Trim21 commented
原本对于user是如何处理的？把`@`替换为user标签后保存？还是在渲染的时候才处理

2022-06-21 07:41 UTC, 22earth commented
@Trim21 
https://gist.github.com/Trim21/a99dea9fad37392cf1ef68e666cc5211#file-bbcode-php-L1002
原来的处理方式就是全量的正则替换。 

```javascript
const rawUserInputString = '[user=1]sai[/user] @sai ';
const myConverterMap = {};
// 目前解析器能够识别  [user] 。如果解析器处理 @  ，又会引用邮箱相关的问题。所有我觉得不应该这块逻辑塞入解析器。
let output = render(rawUserInputString,  myConverterMap)
// 这里可以正则替换一下 @sai 
output = replaceMention(output)
```

2022-06-21 08:28 UTC, Trim21 commented
我刚想到这个at还要发通知，在后端也得解析一遍bbcode...

2022-06-29 15:33 UTC, Ayase-252 approved these changes
还有后续调整吗？

2022-06-30 01:39 UTC, 22earth commented
> 还有后续调整吗？

解析 at 逻辑没写。不太确定是不是需要调用接口  @22earth

2022-06-30 01:44 UTC, Trim21 commented
> > 还有后续调整吗？
> 
> 解析 at 逻辑没写。不太确定是不是需要调用接口

不需要吧，解析出来 at 了哪些用户就可以了。至于后面怎么处理at也还不需要放到这个PR里。

2022-06-30 01:51 UTC, 22earth commented
> > > 还有后续调整吗？
> > 
> > 
> > 解析 at 逻辑没写。不太确定是不是需要调用接口
> 
> 不需要吧，解析出来 at 了哪些用户就可以了。至于后面怎么处理at也还不需要放到这个PR里。

我的想法是不在这个 pr 里面解析 at。利用这个 pr 解析结果，加上判断是否 at 了有效的人，再渲染一次。

2022-06-30 02:00 UTC, Trim21 commented
所以现在（这个PR）是在解析前做了 `@sai` 到 `[user=1]sai[/user]` 的替换，然后把后者作为正常的 bbcode 解析渲染的？

2022-06-30 02:13 UTC, 22earth commented
现在是输入  `[user=1]sai[/user]`  转换成 `<a href="/user/1" class="l">@sai</a>`
输入 `[user]sai[/user]`  转换成 `<a href="/user/sai" class="l">@sai</a>`
输入 `@sai` 没有做处理。没做处理的原因是可能要解析 email，我没想到合适的方案，会扰乱现有的逻辑。
突然想到 email 只判断 `@xx.yy` 里面有 `.` 就当成 email, 不知道可能不

2022-06-30 02:21 UTC, Trim21 commented
看了一下数据库里保存的bbcode，是直接存了 `[user=sai]Sai[/user]` 这样的。

后面用户在输入框里 `@` 的时候处理用户输入然后转一下，就不需要在这个PR里面处理 `@` 了

2022-06-30 02:23 UTC, Trim21 approved these changes

2022-06-30 15:36 UTC, merged