build: use dev api for preview
bangumi/frontend pull request #115
Opened 2022-09-01 14:48 UTC by Ayase-252

使用 `https://dev.bgm38.com` 来 preview

2022-09-01 15:38 UTC, cokemine approved these changes

2022-09-01 16:04 UTC, Trim21 commented
登录的post地址错了

2022-09-04 13:05 UTC, Trim21 commented
我暂时连不上hcaptcha了（

2022-09-04 13:19 UTC, Trim21 commented
session好像不太正常 🤔

2022-09-05 15:22 UTC, Trim21 commented
设置了 `secure; SameSite=None` 🤔 也没发送cookies

2022-09-05 16:08 UTC, Trim21 requested changes
cookies问题

2022-09-13 13:21 UTC, Trim21 approved these changes

2022-09-13 13:23 UTC, Ayase-252 commented
话说有可以用的用户表吗？

2022-09-13 13:24 UTC, Trim21 commented
目前就只有树洞账号这一个

2022-09-13 13:25 UTC, Trim21 commented
可以在dev-env里面加

2022-09-13 13:27 UTC, Ayase-252 commented
哦。。

2022-09-13 13:27 UTC, merged