refactor(website): router structure
bangumi/frontend pull request #130
Opened 2022-10-31 14:30 UTC by FoundTheWOUT

Base #126

2022-11-02 12:38 UTC, Ayase-252 approved these changes

2022-11-02 12:39 UTC, Ayase-252 requested changes
Error: src/components/GlobalLayout/index.tsx(6,30): error TS2314: Generic type 'PropsWithChildren' requires 1 type argument(s).

build 有问题

2022-11-02 12:45 UTC, FoundTheWOUT commented
![LM4$DW}B18JIY5DM`0VPY}O](https://user-images.githubusercontent.com/47922588/199493046-b7449076-2e98-437f-b80e-717af4edbd9e.jpg)

2022-11-02 13:00 UTC, cokemine commented on packages/website/src/pages/index.tsx
>    }
登录之后只显示 Hi! username了

2022-11-02 13:03 UTC, FoundTheWOUT commented on packages/website/src/pages/index.tsx
>    }
确实是这样，因为现在不知道这个 UserHome 组件怎么处理。现在的话是要分登录态和未登录态吗 @Ayase-252

2022-11-02 13:11 UTC, Ayase-252 commented on packages/website/src/pages/index.tsx
>    }
要吧，但是现在没具体设计

2022-11-02 13:12 UTC, FoundTheWOUT commented on packages/website/src/pages/index.tsx
>    }
但是原站的话，未登录也是可以浏览的吧

2022-11-02 13:20 UTC, cokemine commented on packages/website/src/pages/index.tsx
>    }
在 index/index.tsx 判断是否登录展现不同内容把

2022-11-02 13:35 UTC, Ayase-252 commented on packages/website/src/pages/index.tsx
>    }
看原站的话，登录和未登录看到的内容差别挺大的，感觉分开好一点。。

2022-11-02 13:37 UTC, FoundTheWOUT commented on packages/website/src/pages/index.tsx
>    }
确实哦，刚刚登出看了一下😅

2022-11-02 13:41 UTC, cokemine commented on packages/website/src/pages/index.tsx
>    }
确实。。不过主要是主页的差距比较大。肯定和登录时是不能复用的

2022-11-02 14:16 UTC, cokemine approved these changes

2022-11-03 02:54 UTC, Ayase-252 approved these changes

2022-11-03 02:56 UTC, merged