refactor(website): ErrorBoundary
bangumi/frontend pull request #305
Opened 2023-01-09 08:35 UTC by FoundTheWOUT

2023-01-09 12:09 UTC, trim21 commented on packages/website/src/components/ErrorBoundary.tsx
> +    if (error?.status) {
会的，比如出现js错误有可能抛个type error

2023-01-09 12:59 UTC, FoundTheWOUT commented
也不知道咋设计了😅

2023-01-09 16:05 UTC, trim21 commented
> 也不知道咋设计了😅

不用设计了，直接吧原始错误显示出来就行了…

2023-01-10 01:49 UTC, FoundTheWOUT commented
直接显示出来吗，会不会太粗暴了。。那到时候还是得加个返回首页，返回上一页之类的按钮吧

2023-01-10 01:51 UTC, trim21 commented
> 直接显示出来吗，会不会太粗暴了。。那到时候还是得加个返回首页，返回上一页之类的按钮吧

> 遇到未知错误，在提交错误信息时请附上以下内容：（注意敏感信息）
> ...

2023-01-10 01:53 UTC, trim21 commented
> > 直接显示出来吗，会不会太粗暴了。。那到时候还是得加个返回首页，返回上一页之类的按钮吧
> 
> > 遇到未知错误，在提交错误信息时请附上以下内容：（注意敏感信息）
> > ...

啊你是说这个。。。那我 @vistaing

2023-01-10 01:56 UTC, trim21 commented
现在用得cf还有个cf-ray的请求头作为request id，要是能一起显示出来就最好了（

太麻烦的话就算了

2023-01-11 07:57 UTC, vistaing commented
> 直接显示出来吗，会不会太粗暴了。。那到时候还是得加个返回首页，返回上一页之类的按钮吧

我先捣鼓一个页面出来，文本日后还可微调（

2023-03-01 11:32 UTC, trim21 commented
@vistaing 话说这个有进展吗... 先搞一下这个吧

2023-03-01 11:36 UTC, FoundTheWOUT commented
Wiki Editor那边还没做好吧，那个貌似是wip ？一个一个来吧🧐

2023-03-01 11:38 UTC, trim21 commented
🧐 那这个和Wiki Editor以外的先放一放

2023-03-03 17:10 UTC, trim21 commented
这个的设计应该OK了

2023-03-06 13:56 UTC, trim21 requested changes

2023-03-06 13:58 UTC, FoundTheWOUT commented on packages/website/src/components/ErrorBoundary/index.tsx
> +            : '发生未知错误'}
request id 是啥，请求路径吗

2023-03-06 13:59 UTC, trim21 commented on packages/website/src/components/ErrorBoundary/index.tsx
> +            : '发生未知错误'}
> request id 是啥，请求路径吗

`cf-ray` header，如果有的话

2023-03-06 14:01 UTC, FoundTheWOUT commented on packages/website/src/components/ErrorBoundary/index.tsx
> +            : '发生未知错误'}
我要怎么去测试这个东西🤔

2023-03-06 14:03 UTC, trim21 commented on packages/website/src/components/ErrorBoundary/index.tsx
> +            : '发生未知错误'}
> 我要怎么去测试这个东西🤔

msw不能返回header吗…

2023-03-06 14:05 UTC, trim21 commented on packages/website/src/components/ErrorBoundary/index.tsx
> +            : '发生未知错误'}
> 我要怎么去测试这个东西🤔

对哦，好像是没办法测试 🤔 

我加个路由返回500用来测试吧

2023-03-06 14:10 UTC, trim21 commented on packages/website/src/components/ErrorBoundary/index.tsx
> +            : '发生未知错误'}
> 我加个路由返回500用来测试吧

还是msw吧，或者设置一下vite server（

2023-03-06 14:37 UTC, trim21 requested changes

2023-03-06 14:37 UTC, trim21 commented on packages/website/src/components/ErrorBoundary/index.tsx
> +    const { fallback } = this.props;
这个fallback也 🤔 感觉需要考虑一下只有某些请求才用传进来的fallback？

2023-03-06 14:56 UTC, FoundTheWOUT commented on packages/website/src/components/ErrorBoundary/index.tsx
> +            : '发生未知错误'}
oazapfts 中的 HttpError 没有抛出 http 头，可能要想办法拿到这个请求才行

2023-03-06 14:57 UTC, FoundTheWOUT commented on packages/website/src/components/ErrorBoundary/index.tsx
> +    const { fallback } = this.props;
现在这个 fallback 就是可选的呀

2023-03-06 14:59 UTC, trim21 commented on packages/website/src/components/ErrorBoundary/index.tsx
> +            : '发生未知错误'}
那先这样吧，我去那边提的PR，后面再加

2023-03-06 15:11 UTC, cokemine commented on packages/website/src/components/ErrorBoundary/index.tsx
> +            : error.message
```suggestion
            : error.message ?? '发生未知错误'
```

2023-03-06 15:15 UTC, trim21 commented on packages/website/src/components/ErrorBoundary/index.tsx
> +            : '发生未知错误'}
https://github.com/oazapfts/oazapfts/pull/391 看看哪边先合 (bgm38)

2023-03-06 15:16 UTC, trim21 commented on packages/website/src/components/ErrorBoundary/index.tsx
> +    const { fallback } = this.props;
> 现在这个 fallback 就是可选的呀

比如这个 https://github.com/bangumi/frontend/pull/305/files#diff-8490bd56aa3e80bf9a816fdb6447caee1d5a9ab1461358a3977c9d13ea504d17

api响应一个500的话就是显示not found了吧

2023-03-06 15:19 UTC, cokemine commented on packages/website/src/components/ErrorBoundary/ErrorLayout.tsx
> +          <Typography.Link to='..'>返回上页</Typography.Link>
返回上页应该是返回 history 的上页吧，有可能不是从 ../ 跳转过来的

2023-03-06 15:21 UTC, cokemine commented on packages/website/src/components/ErrorBoundary/ErrorLayout.tsx
> +          <Typography.Link to='..'>返回上页</Typography.Link>
而且 ../ 不一定有页面（

2023-03-06 15:21 UTC, trim21 commented on packages/website/src/components/ErrorBoundary/index.tsx
> +            : error.message
```suggestion
            : error.data?.message ?? error.message ?? '发生未知错误'
```

2023-03-06 21:33 UTC, trim21 commented
移动端效果有点问题…

2023-03-06 23:33 UTC, FoundTheWOUT commented on packages/website/src/components/ErrorBoundary/ErrorLayout.tsx
> +          <Typography.Link to='..'>返回上页</Typography.Link>
有道理，我以为这个..操作符是history 退回🥲，原来它是按路径的

2023-03-07 03:03 UTC, FoundTheWOUT commented on packages/website/src/components/ErrorBoundary/index.tsx
> +    const { fallback } = this.props;
是会这样，这个问题的话我觉得可以在 withErrorBoundary 的时候去控制这个粒度。不过感觉也可以直接在ErrorBoundary 里做，就如果是 500 的话就不用 fallback 了，你觉得呢。

2023-03-07 11:17 UTC, trim21 commented on .eslintrc.js
> +        '@typescript-eslint/no-unsafe-assignment': 'off',
这个两个规则怎么禁用了

2023-03-07 12:04 UTC, trim21 commented on packages/website/src/components/ErrorBoundary/index.tsx
> +    const { fallback } = this.props;
可以用 `Record<number, JSX>` 作为 fallback ？

2023-03-07 12:08 UTC, FoundTheWOUT commented on .eslintrc.js
> +        '@typescript-eslint/no-unsafe-assignment': 'off',
![image](https://user-images.githubusercontent.com/47922588/223417768-271060ed-a1db-4ebf-8177-5aec0bdee131.png)

2023-03-07 12:12 UTC, trim21 commented on .eslintrc.js
> +        '@typescript-eslint/no-unsafe-assignment': 'off',
单独在这一行禁用呗（

2023-03-07 15:53 UTC, trim21 approved these changes

2023-03-07 15:54 UTC, trim21 requested changes
返回上页跳出网站了。。（

2023-03-07 15:55 UTC, FoundTheWOUT commented
> 返回上页跳出网站了。。（

如果history上一页是blank（那返回blank感觉也挺合理的吧

2023-03-07 15:56 UTC, trim21 commented
> > 返回上页跳出网站了。。（
> 
> 如果history上一页是blank（那返回blank感觉也挺合理的吧

仔细一想浏览器也拿不到浏览纪录？那无所谓了

2023-03-07 16:06 UTC, trim21 commented on packages/website/src/components/ErrorBoundary/index.tsx
> +    const { fallback } = this.props;
那只有这个问题了（

2023-03-07 16:09 UTC, FoundTheWOUT commented on packages/website/src/components/ErrorBoundary/index.tsx
> +    const { fallback } = this.props;
这个已经做好了呀😂

2023-03-07 16:12 UTC, trim21 commented on packages/website/src/components/ErrorBoundary/index.tsx
> +    const { fallback } = this.props;
啊，没注意到

2023-03-07 16:13 UTC, trim21 submitted a review, later dismissed

2023-03-08 03:37 UTC, Ayase-252 commented on packages/website/src/components/ErrorBoundary/index.tsx
> +      let fb; // fb can be a JSX.Element or a function return a JSX.Element
这个注释可以转成类型声明？另外是 httpErrorFallback? 看下面这个应该只有 error 是 HttpError 才会生效。

2023-03-08 03:37 UTC, Ayase-252 commented on packages/website/src/components/ErrorBoundary/style.module.less
> +.errorContainer {
可以用 error-container 形式了？才发现 vite localsConventions 默认是 camelCase

2023-03-08 03:41 UTC, FoundTheWOUT commented on packages/website/src/components/ErrorBoundary/index.tsx
> +      let fb; // fb can be a JSX.Element or a function return a JSX.Element
嗯，暂时的话确实只有httperror 才会有fallback

2023-03-08 06:17 UTC, FoundTheWOUT commented on packages/website/src/components/ErrorBoundary/style.module.less
> +.errorContainer {
camelCase 的话 tsx 不就要写 `style['error-container']` 这样嘛

2023-03-08 07:02 UTC, Ayase-252 commented on packages/website/src/components/ErrorBoundary/style.module.less
> +.errorContainer {
不用，tsx 可以照样写 style.erroContainer

2023-03-08 07:04 UTC, FoundTheWOUT commented on packages/website/src/components/ErrorBoundary/style.module.less
> +.errorContainer {
刚刚试了以下，不太行的样子

2023-03-08 07:40 UTC, Ayase-252 commented on packages/website/src/components/ErrorBoundary/style.module.less
> +.errorContainer {
奇怪，设置下呢？https://vitejs.dev/guide/features.html

2023-03-09 03:18 UTC, Ayase-252 approved these changes

2023-03-09 07:52 UTC, trim21 approved these changes

2023-03-09 07:54 UTC, merged