feat: redirect to last page after successful login
bangumi/frontend pull request #359
Opened 2023-02-13 08:27 UTC by y-young

2023-02-13 12:48 UTC, Ayase-252 commented on packages/website/src/pages/login/index.tsx
> +    }
这个功能感觉不需要吧，万一上一页是个错误页

2023-02-13 12:51 UTC, y-young commented on packages/website/src/pages/login/index.tsx
> +    }
这个主要是在用户自己想登录的时候，比如现在这样，在小组讨论页面想测试发帖，手动点完登录后可以跳转回来，不需要导航栏加额外参数
如果是错误页可以直接传 `backTo` 参数过去

2023-02-13 12:57 UTC, Ayase-252 commented on packages/website/src/pages/login/index.tsx
> +    }
```suggestion
const backTo = searchParams.get('backTo')
    // 如果有 backTo 参数，则跳转到指定的页面
    if (backTo) {
      navigate(backTo, { replace: true });
    }
```
这样的话不用加 ! ?

2023-02-13 13:01 UTC, y-young commented on packages/website/src/pages/login/index.tsx
> +    }
确实，我傻了（

2023-02-13 15:34 UTC, trim21 commented
back如果是完整的url会怎么样，会转跳到其他网站吗？

2023-02-13 15:37 UTC, y-young commented
> back如果是完整的url会怎么样，会转跳到其他网站吗？

好问题，但是并不会，你可以试一试

2023-02-13 16:03 UTC, Ayase-252 approved these changes

2023-02-13 16:04 UTC, trim21 commented
> > back如果是完整的url会怎么样，会转跳到其他网站吗？
> 
> 好问题，但是并不会，你可以试一试

那就ok

2023-02-14 22:01 UTC, trim21 requested changes
`https://pr-359-sites--bangumi-next.netlify.app/login?backTo=https://github.com/` 登录后会转跳到 `https://pr-359-sites--bangumi-next.netlify.app/login/https://github.com/`。

感觉检查一下不是 `.startsWith('/')` 就转跳回首页就会好了？

2023-02-15 01:47 UTC, trim21 approved these changes

2023-02-15 03:28 UTC, Ayase-252 requested changes
加个测试用例？

2023-02-15 04:05 UTC, trim21 approved these changes

2023-02-15 04:15 UTC, Ayase-252 approved these changes

2023-02-15 08:29 UTC, merged