feat: edit group reply
bangumi/frontend pull request #426
Opened 2023-02-26 09:28 UTC by y-young

Tracking: #112

2023-02-26 12:29 UTC, trim21 commented
https://pr-426-sites--bangumi-next.netlify.app/group/reply/2177421/edit b38

2023-02-27 17:04 UTC, trim21 commented
感觉可以改一下 API，直接返回对应的帖子标题，前端就不需要请求两个 API 了

2023-03-03 17:38 UTC, trim21 requested changes
等着改一下API的相应，没必要额外请求一次帖子内容。

2023-03-07 14:07 UTC, y-young commented
才发现 API 3 天前就改好了(bgm38)

然而现在有个问题，如果用 useGroupTopic 的话必定会请求一次帖子数据，如果不用 useGroupTopic 的话似乎没法让主题里的回复内容在返回之前刷新，试了全局的 mutate 和 useSWRMutation 貌似都不行，刚返回的时候先看到还是旧数据。

2023-03-07 14:22 UTC, trim21 commented
> 才发现 API 3 天前就改好了(bgm38)
> 
> 然而现在有个问题，如果用 useGroupTopic 的话必定会请求一次帖子数据，如果不用 useGroupTopic 的话似乎没法让主题里的回复内容在返回之前刷新，试了全局的 mutate 和 useSWRMutation 貌似都不行，刚返回的时候先看到还是旧数据。

没有fetch过数据的话直接转跳回去不就能自动fetch新数据了吗？SWR应该是这样的吧？

2023-03-07 14:23 UTC, y-young commented
> 没有fetch过数据的话直接转跳回去不就能自动fetch新数据了吗？SWR应该是这样的吧？

是这样，只不过会看到旧数据变成新数据的过程

2023-03-07 14:28 UTC, trim21 commented
> > 没有fetch过数据的话直接转跳回去不就能自动fetch新数据了吗？SWR应该是这样的吧？
> 
> 是这样，只不过会看到旧数据变成新数据的过程

useGroupTopic 放在提交成功之后？

2023-03-07 14:46 UTC, y-young commented
> > 是这样，只不过会看到旧数据变成新数据的过程
> 
> useGroupTopic 放在提交成功之后？

hook 没有放在提交前后之分，如果是 mutate 的话已经是放在提交后了，像之前编辑主题那样用 `await mutate()` 能等到数据刷新后再返回，但用 useSWRMutation 貌似不行

2023-03-07 14:52 UTC, trim21 commented
> > > 是这样，只不过会看到旧数据变成新数据的过程
> > 
> > 
> > useGroupTopic 放在提交成功之后？
> 
> hook 没有放在提交前后之分，如果是 mutate 的话已经是放在提交后了，像之前编辑主题那样用 `await mutate()` 能等到数据刷新后再返回，但用 useSWRMutation 和 useSWRConfig 里的 mutate 貌似不行

我试了一下现在实际的网络请求 🤔

`/group/topic/371602` 
get topic

`/group/reply/2177440/edit`
get post
get topic （可以不请求）

提交
put post
get post（可以不请求）

转跳回去
get topic

2023-03-07 15:02 UTC, cokemine commented
> > > > 是这样，只不过会看到旧数据变成新数据的过程
> > > 
> > > 
> > > useGroupTopic 放在提交成功之后？
> > 
> > 
> > hook 没有放在提交前后之分，如果是 mutate 的话已经是放在提交后了，像之前编辑主题那样用 `await mutate()` 能等到数据刷新后再返回，但用 useSWRMutation 和 useSWRConfig 里的 mutate 貌似不行
> 
> 我试了一下现在实际的网络请求 🤔
> 
> `/group/topic/371602` get topic get group profile
> 
> 点击编辑转跳或者直接访问 `/group/reply/2177440/edit` get post get topic （可以不请求）
> 
> 提交 put post get post（可以不请求）
> 
> 转跳回去 get topic get group profile

用 useSWRImmutable 就可以不重新请求那些数据不变的API了

2023-03-07 15:07 UTC, trim21 requested changes
这个页面需要登录...

2023-03-07 15:09 UTC, cokemine commented
> 这个页面需要登录...

还要判断下登录的用户是不是这个发这个评论的人（

2023-03-07 15:17 UTC, trim21 commented
> 用 useSWRImmutable 就可以不重新请求那些数据不变的API了

这里的请求的数据都是会变得

2023-03-07 15:25 UTC, cokemine commented
> > 用 useSWRImmutable 就可以不重新请求那些数据不变的API了
> 
> 这里的请求的数据都是会变得

可以只在不需要重新请求的时候hook设置 revalidateIfStale 为 false 就会只返回缓存内容了。需要重新请求的时候默认还是重新请求 API


> 是这样，只不过会看到旧数据变成新数据的过程

可能需要 https://swr.vercel.app/docs/mutation#optimistic-updates

2023-03-07 15:33 UTC, trim21 commented on packages/website/src/pages/index/group/reply/[id]/edit.tsx
> +      mutate({ ...data, text });
这个可以用 `refreshWhenHidden` 吧？

2023-03-07 15:34 UTC, y-young commented
useSWRImmutable 仍然会请求数据，这里是想让这个页面根本不请求帖子数据

useSWRMutation 不会请求数据，然而 `await mutate()` 并没有让回复内容在跳转之前更新，全局配置 suspense 也不行

用 optimistic update 可以让 UI 不显示旧内容，然而这样不是还得获取帖子数据……

2023-03-07 15:35 UTC, y-young commented on packages/website/src/pages/index/group/reply/[id]/edit.tsx
> +      mutate({ ...data, text });
这个是更新回复内容，useGroupPost 这个 hook 现在没有其他地方用，这样更新也不会发后端请求，没问题吧

2023-03-07 15:36 UTC, trim21 commented on packages/website/src/pages/index/group/reply/[id]/edit.tsx
> +      mutate({ ...data, text });
哦好像不可以

2023-03-07 15:40 UTC, trim21 commented
难道 swr 做不到这个吗（

2023-03-07 15:48 UTC, cokemine commented
> useSWRImmutable 仍然会请求数据，这里是想让这个页面根本不请求帖子数据
> 
> useSWRMutation 不会请求数据，然而 `await mutate()` 并没有让回复内容在跳转之前更新，全局配置 suspense 也不行
> 
> 用 optimistic update 可以让 UI 不显示旧内容，然而这样不是还得获取帖子数据……

我试了试加上 revalidateIfStale false 之后从 /group/topic/371602 访问 /group/reply/2177440/edit 不会再请求 get topic 了啊。
如果初次访问就是 /group/reply/2177440/edit 不可能不请求 topic 吧，不知道帖子的标题

2023-03-07 15:49 UTC, y-young commented
登录和权限检查直接抛异常了，错误信息的显示等 ErrorBoundary 那个 PR

> 难道 swr 做不到这个吗（

理论上应该是可以的（
看得有点晕了，明天再搞（

2023-03-07 15:51 UTC, y-young commented
> 我试了试加上 revalidateIfStale false 之后从 /group/topic/371602 访问 /group/reply/2177440/edit 不会再请求 get topic 了啊。 

现在其实也不会

> 如果初次访问就是 /group/reply/2177440/edit 不可能不请求 topic 吧，不知道帖子的标题

现在让获取 post 的那个 API 顺带返回了

2023-03-07 16:24 UTC, cokemine commented
> 现在其实也不会

现在是会重新请求的，默认行为是先返回缓存然后请求api检查有没有更新

> 现在让获取 post 的那个 API 顺带返回了

没看前文（。也就是现在useGroupTopic在这只是为了刷新帖子才使用的。我看看

2023-03-07 16:26 UTC, y-young commented
> 现在是会重新请求的，默认行为是先返回缓存然后请求api检查有没有更新

哦对，是 useSWRMutation 不会

> 也就是现在useGroupTopic在这只是为了刷新帖子才使用的

没错

2023-03-07 16:57 UTC, trim21 commented
是不是得手动封装一下 useState 之类的（

2023-03-08 02:44 UTC, FoundTheWOUT commented
在最后一行加这样？可能得问问设计师（

2023-03-08 03:31 UTC, y-young commented
应该搞定了，记录一下过程：

如果使用 useSWRMutation 可以避免请求 topic，但昨天测试时无法及时更新 UI，把全局的 cache 打出来后发现是 cache 没有更新，原因是 populateCache 参数默认为 false，改成 true 就可以了

然而使用 useSWRMutation 仍然有个问题，在编辑回复页 mutate 时会请求一次帖子数据，在跳转回帖子时还会再请求一次，理论上时间相近的两次请求应该会去重，但不知道这里为什么没有

所以现在的方法时用全局的 mutate（避免调用 useGroupTopic），data 参数可以接收一个 mutate 函数，可以对帖子内容进行乐观更新，这样就省去了一次请求，在跳转回帖子后会在后台 revalidate，有问题会 rollback（如果这个请求不需要的话应该也可以去掉）

此外发现 mutate reply 也会发一次请求，现在把 revalidate 改成 false 就不会了

2023-03-09 16:17 UTC, trim21 commented
等先合了另一个PR吧，改成error toast

2023-03-09 16:55 UTC, trim21 approved these changes

2023-03-10 03:26 UTC, Ayase-252 commented on packages/design/components/Topic/__test__/Comment.spec.tsx
> +    )?.textContent;
这个是不是用 getByText 就行了？

2023-03-10 03:26 UTC, Ayase-252 commented on packages/website/src/pages/index/group/reply/[id]/edit.tsx
> +  const postId = Number(id);
parseInt

2023-03-10 03:35 UTC, y-young commented on packages/design/components/Topic/__test__/Comment.spec.tsx
> +    )?.textContent;
用 getByText 会选到子评论

2023-03-10 04:08 UTC, Ayase-252 commented on packages/website/src/pages/index/group/reply/[id]/edit.tsx
>    if (!id || Number.isNaN(Number(id))) {
这个也 parseInt 吧 或者把下面的 postId 提上来

2023-03-10 12:03 UTC, trim21 commented on packages/website/src/pages/index/group/reply/[id]/edit.tsx
> +  const postId = Number(id);
应该自己写个parse int方法，标准库的parseInt太宽松了🤔

2023-03-11 15:43 UTC, trim21 commented
`parseInt('12abc') === 12`

2023-03-17 13:48 UTC, trim21 approved these changes

2023-03-24 08:50 UTC, Ayase-252 approved these changes

2023-03-24 08:56 UTC, merged