fix: collapse & disable reply on deleted comments
bangumi/frontend pull request #429
Opened 2023-02-27 04:30 UTC by y-young

- 折叠已删除的子评论
- 已删除评论不显示回复等按钮
- 组件拆分重构

2023-02-27 04:54 UTC, cokemine approved these changes

2023-02-27 04:55 UTC, cokemine approved these changes

2023-02-27 12:45 UTC, Ayase-252 commented on packages/design/components/Topic/Comment.tsx
> +          </Button>
没做吗，先隐藏下？

2023-02-27 12:47 UTC, y-young commented on packages/design/components/Topic/Comment.tsx
> +          </Button>
为啥要隐藏？接下来要做也可以啊

2023-02-27 13:23 UTC, Ayase-252 commented on packages/design/components/Topic/Comment.tsx
> +          </Button>
不容易看清楚啥功能做了还是没做，怕带一个没功能的按钮上线（

2023-02-27 13:23 UTC, Ayase-252 approved these changes

2023-02-27 13:24 UTC, Ayase-252 commented on packages/design/components/Topic/Comment.tsx
> +          </Button>
看后面有 PR 先这样吧

2023-02-27 13:40 UTC, y-young commented on packages/design/components/Topic/Comment.tsx
> +          </Button>
> 不容易看清楚啥功能做了还是没做，怕带一个没功能的按钮上线（

这按钮从小组讨论页做好开始就在上面了（

2023-02-27 19:25 UTC, trim21 commented
![image](https://user-images.githubusercontent.com/13553903/221662909-206e70e1-53b9-479a-8915-979874620517.png)

这个行高的padding是不是多了点名

2023-02-27 19:26 UTC, trim21 requested changes
标一下 Request changes 防止被bot合并了

2023-02-27 19:32 UTC, trim21 approved these changes

2023-02-28 02:24 UTC, y-young commented
> 这个上下的padding是不是多了点（看了一下这个是设计问题）

我觉得刚好

> 评论之间这个虚线是咋来的？在设计稿里没看到 🤔

设计稿里不是有么，只是灰色背景的那个图看不出来而已

2023-03-01 04:30 UTC, merged