test: e2e test
bangumi/frontend pull request #439
Opened 2023-03-10 15:39 UTC by cijiugechu

2023-03-10 15:56 UTC, trim21 commented
这个 vitest-github-actions-reporter 怎么重复创建了这么多测试失败的 annotations

2023-03-10 15:59 UTC, trim21 commented
顺便改一下bot的label规则 https://github.com/bangumi/frontend/blob/00b8babae1a1b2512cf5eec9293297dc81bef991/.github/mergify.yml#L105

2023-03-10 16:04 UTC, cijiugechu commented
> 

好像是刚开始没在vitest里排除掉e2e的路径

2023-03-10 16:07 UTC, cijiugechu commented
> 顺便改一下bot的label规则
> 
> https://github.com/bangumi/frontend/blob/00b8babae1a1b2512cf5eec9293297dc81bef991/.github/mergify.yml#L105

这个test好像已经包含了e2e的，你的想法是分作不同的label吗

2023-03-10 16:13 UTC, trim21 commented on packages/website/playwright.config.ts
> +  timeout: process.env.CI ? 180 * 1000 : 180 * 1000,
这里看起来没有判断是否处于CI环境的必要？

2023-03-10 17:54 UTC, trim21 commented
e2e是依赖stage api的？

2023-03-10 20:46 UTC, trim21 requested changes

2023-03-10 20:46 UTC, trim21 commented on packages/website/e2e/group.spec.ts
> +    await page.getByRole('link', { name: '--------主题编辑测试--------' }).click();
不能这么写，stage api可能会重置数据的。

2023-03-11 13:56 UTC, trim21 approved these changes

2023-03-13 03:11 UTC, Ayase-252 commented on packages/website/e2e/group.spec.ts
> +    await page.getByPlaceholder('想聊点什么的呢…').press('Enter');
要不写个 page object....看起来太暴力了

2023-03-13 10:13 UTC, cijiugechu commented on packages/website/e2e/group.spec.ts
> +    await page.getByPlaceholder('想聊点什么的呢…').press('Enter');
[codegen](https://playwright.dev/docs/codegen-intro)生成的，感觉多数场景也需要这种方式

2023-03-13 11:32 UTC, Ayase-252 commented on packages/website/e2e/group.spec.ts
> +    await page.getByPlaceholder('想聊点什么的呢…').press('Enter');
可读性感觉有点问题。如果要更新点啥功能，感觉都看不懂这个测试在干啥。

2023-03-14 10:59 UTC, cijiugechu commented on packages/website/e2e/group.spec.ts
> +    await page.getByPlaceholder('想聊点什么的呢…').press('Enter');
改成一次性填入文本了

2023-03-15 03:45 UTC, Ayase-252 commented on packages/website/e2e/group.spec.ts
> +    await page.getByRole('button', { name: '登录' }).click();
这个登录能抽个方法啥的吗？我看下面也用了

2023-03-15 16:06 UTC, Ayase-252 approved these changes

2023-03-15 16:11 UTC, merged