Notification
bangumi/frontend pull request #473
Opened 2023-03-17 02:55 UTC by FoundTheWOUT

follow up #239 
close #236

2023-03-17 22:12 UTC, trim21 commented
客户端更新了

2023-03-18 07:03 UTC, trim21 requested changes

2023-03-18 07:03 UTC, trim21 commented on packages/website/src/hooks/use-notify.ts
> +      transports: ['websocket'],
不行，必须有polling。netfliy不支持websocket

2023-03-18 07:05 UTC, trim21 commented on packages/website/src/hooks/use-notify.ts
> +      transports: ['websocket'],
需要放在第二个作为fallback

2023-03-18 07:05 UTC, FoundTheWOUT commented on packages/website/src/hooks/use-notify.ts
> +      transports: ['websocket'],
这个 socket 不是在 client 的吗，和 netfliy 有什么关系🤔

2023-03-18 07:06 UTC, trim21 commented on packages/website/src/hooks/use-notify.ts
> +      transports: ['websocket'],
https://github.com/bangumi/frontend/pull/473#issuecomment-1473044317

2023-03-18 07:55 UTC, FoundTheWOUT commented on packages/website/src/hooks/use-notify.ts
> +      transports: ['websocket'],
我看你原来是 onerror 的时候才转的 polling ？不按原来的吗

2023-03-18 07:59 UTC, trim21 commented on packages/website/src/hooks/use-notify.ts
> +      transports: ['websocket'],
啊，我忘记了…

看到下面注释掉那行的地方我以为这里是直接把polling写进去了

2023-03-18 08:00 UTC, trim21 commented on packages/website/src/hooks/use-notify.ts
> +      transports: ['websocket'],
看了下文档，现在这样和我原来写的onerror效果差不多

2023-03-19 05:24 UTC, trim21 commented
"Empty data Design" 是啥

2023-03-19 06:26 UTC, FoundTheWOUT commented
> "Empty data Design" 是啥

就是空数据设计，现在直接就显示没有数据

2023-03-19 06:33 UTC, trim21 commented
设计稿里下面的通知列表就直接不显示了呗。

2023-03-27 08:12 UTC, trim21 commented
短信收发这个链接先加个TODO隐藏一下吧

2023-03-27 08:13 UTC, trim21 commented
这个 一键全部已读 应该只标记目前用户看到的未读通知，而不是清空全部的...

2023-03-27 08:15 UTC, trim21 commented
> > 这个 一键全部已读 应该只标记目前用户看到的未读通知，而不是清空全部的...
> 
> 这个 API 不一样的吗😅，我以为清空就是设置为已读

一样的，我是说应该传一下 id，否则如果未知通知太多的话用户还没看到的通知也会被标记成已读。

2023-03-27 10:02 UTC, trim21 commented
筛选也隐藏了加个TODO吧

2023-03-27 10:05 UTC, FoundTheWOUT commented on packages/website/src/pages/index/notifications/index.tsx
> +      <div className={style.subtile}>更新于 2022-9-20 10:25</div>
😅稍等改下

2023-03-27 11:47 UTC, FoundTheWOUT commented on packages/website/src/pages/index/notifications/index.tsx
> +      <div className={style.subtile}>更新于 2022-9-20 10:25</div>
这个更新于应该显示什么时间？从 ws onmessage 的时候更新吗

2023-03-27 16:34 UTC, trim21 commented
在 https://github.com/bangumi/frontend/issues/438 实现之后应该在收到通知时给标题加上一个 `(n) ...` 的前缀

2023-03-31 07:39 UTC, FoundTheWOUT commented
突然想到一个问题，这个修改 title 应该是监听 socket 然后动态更新当前 title 吧，感觉和 438 没啥关系bgm38

2023-03-31 07:55 UTC, y-young commented
用 useEffect 在 notifyCount 和 document.title 变化的时候更新标题是不是更好一些？

2023-03-31 07:57 UTC, FoundTheWOUT commented
> 用 useEffect 在 notifyCount 和 document.title 变化的时候更新标题是不是更好一些？

有道理的

2023-03-31 08:00 UTC, FoundTheWOUT commented
document.title 在变更时不会触发 rerender 吧，怎么保证这个 effect 会重新执行

2023-03-31 08:02 UTC, y-young commented
> document.title 在变更时不会触发 rerender 吧，怎么保证这个 effect 会重新执行

不行的话就把 HelmetProvider 改成一个保存了 title 的 Context？

2023-03-31 08:07 UTC, y-young commented
> > 不行的话就把 HelmetProvider 改成一个保存了 title 的 Context？
> 
> react-helmet-async 有没有直接 useTitle 之类的东西，就是把 title 转成 state 之类的

这个我之前找过，不论是原版还是新版都没有

2023-03-31 08:21 UTC, FoundTheWOUT commented
> 这个我之前找过，不论是原版还是新版都没有

突然发现这个 Header 组件一直在 rerender，原因是用 react-router 的 hook。所以现在去监听 document.title 这个依赖是没问题的，感觉在这个 notify hook 里用以下 react-router 的 hook 更好，不过现在就 Header 一个在用，问题应该不大。

2023-03-31 08:24 UTC, y-young commented
> 突然发现这个 Header 组件一直在 rerender，原因是用 react-router 的 hook。所以现在去监听 document.title 这个依赖是没问题的，感觉在这个 notify hook 里用以下 react-router 的 hook 更好，不过现在就 Header 一个在用，问题应该不大。

也对，NavLink 之类的需要随路由刷新，怪不得我之前用 useEffect 试的时候没问题

2023-03-31 08:33 UTC, y-young commented on packages/website/src/components/Header/index.tsx
> +                  [style.iconNotificationNotice!]: true,
这里应该是判断 noticeCount 吧

2023-03-31 12:42 UTC, trim21 commented
> 突然想到一个问题，这个修改 title 应该是监听 socket 然后动态更新当前 title 吧，感觉和 438 没啥关系bgm38

不会互相影响吗？比如这边加了前缀之后因为切换页面导致前缀消失？

我不太了解怎么实现的，只是感觉可能有影响

2023-04-01 08:59 UTC, y-young commented
> > 突然想到一个问题，这个修改 title 应该是监听 socket 然后动态更新当前 title 吧，感觉和 438 没啥关系bgm38
> 
> 不会互相影响吗？比如这边加了前缀之后因为切换页面导致前缀消失？
> 
> 我不太了解怎么实现的，只是感觉可能有影响

是有这个可能的

想了想可以用 MutationObserver 监听 title 元素的变化，或者在 `<Helmet>` 上加一个 `onChangeClientState` 可以监听状态变化，但只能在具体的 Helmet 示例上用，不能在 HelmetProvider上用

react-helmet-async 的文档写得真不行，硬着头皮去看了看 react-helmet-async 的源码，应该有一个办法实现类似 Context 的效果，就是在 Header 里面放一个 `<Helmet onChangeClientState={console.log} />`，这样页面里设置标题依然会生效，之后的 Helmet 示例也会继承这里的参数

2023-04-01 09:45 UTC, trim21 commented
> > > 突然想到一个问题，这个修改 title 应该是监听 socket 然后动态更新当前 title 吧，感觉和 438 没啥关系bgm38
> > 
> > 
> > 不会互相影响吗？比如这边加了前缀之后因为切换页面导致前缀消失？
> > 我不太了解怎么实现的，只是感觉可能有影响
> 
> 是有这个可能的
> 
> 想了想可以用 MutationObserver 监听 title 元素的变化，或者在 `<Helmet>` 上加一个 `onChangeClientState` 可以监听状态变化，但只能在具体的 Helmet 示例上用，不能在 HelmetProvider上用
> 
> react-helmet-async 的文档写得真不行，硬着头皮去看了看源码，应该有一个办法实现类似 Context 的效果，就是在 Header 里面放一个 `<Helmet onChangeClientState={console.log} />`，这样页面里设置标题依然会生效，之后的 Helmet 示例也会继承这里的参数，即多个 Helmet 实例的参数会互相叠加，按渲染次序后者覆盖前者

可以跟现在的Toast一样，把 `react-helmet-async` 封装在一个单独的文件里，外面可以setTitle和setNotifyCount，然后根据当前的title和notifyCount来生成一个真正的title?

2023-04-01 10:02 UTC, y-young commented
> 可以跟现在的Toast一样，把 `react-helmet-async` 封装在一个单独的文件里，外面可以setTitle和setNotifyCount，然后根据当前的title和notifyCount来生成一个真正的title? 这样无论是 `setTitle` 还是 `setNotifyCount` 都会触发title修改，但是不会互相冲突

或者可以直接设置 titleTemplate

2023-04-01 10:04 UTC, trim21 commented
> 或者可以直接设置 titleTemplate

交给你们了!

2023-04-01 10:06 UTC, FoundTheWOUT commented
> 
> 可以跟现在的Toast一样，把 `react-helmet-async` 封装在一个单独的文件里，外面可以setTitle和setNotifyCount，然后根据当前的title和notifyCount来生成一个真正的title? 这样无论是 `setTitle` 还是 `setNotifyCount` 都会触发title修改，但是不会互相冲突

没有太理解这个，如果这样的话是不是也会影响到其它Helmet的使用，就是其它地方也要用这个useTitle，而不能直接Helmet？

2023-04-01 11:19 UTC, trim21 commented
> > 可以跟现在的Toast一样，把 `react-helmet-async` 封装在一个单独的文件里，外面可以setTitle和setNotifyCount，然后根据当前的title和notifyCount来生成一个真正的title? 这样无论是 `setTitle` 还是 `setNotifyCount` 都会触发title修改，但是不会互相冲突
> 
> 没有太理解这个，如果这样的话是不是也会影响到其它Helmet的使用，就是其它地方也要用这个useTitle，而不能直接Helmet？

我只是想到这个问问题来建议一下👀 不是一定要按我说的这么搞

2023-04-03 03:52 UTC, FoundTheWOUT commented
没啥其它问题的话，这个可以合了？

2023-04-03 04:20 UTC, y-young commented
> 没啥其它问题的话，这个可以合了？

看看能不能按 https://github.com/bangumi/frontend/pull/473#issuecomment-1492883638 这个改一下？

2023-04-03 06:13 UTC, trim21 commented
标题可能冲突的问题解决了吗？👀

2023-04-03 07:06 UTC, FoundTheWOUT commented
其实现在也可以吧，测试下来没啥问题。（在 Header 里使用 useNotify 没有冲突问题，原因在注释里已经写了）
刚刚用 Mutation 试着实现了一次，不太行，用 Mutation 会出现循环调用，因为 mutate 的对象就是 observe 的对象。也可能是我不太会写（
在每个 Helmet 上加个参数感觉也比较繁琐，如果是这样的话可能自定义个 Helmet 更好。
我觉得现在不去动 Helmet 也能解决就挺好的……

2023-04-03 07:13 UTC, y-young commented
> 其实现在也可以吧，测试下来没啥问题。（在 Header 里使用 useNotify 没有冲突问题，原因在注释里已经写了） 刚刚用 Mutation 试着实现了一次，不太行，用 Mutation 会出现循环调用，因为 mutate 的对象就是 observe 的对象。也可能是我不太会写（ 在每个 Helmet 上加个参数感觉也比较繁琐，如果是这样的话可能自定义个 Helmet 更好。 我觉得现在不去动 Helmet 也能解决就挺好的……

试试在 Header 里放一个 Helmet，如果有新通知就设置属性 ```titleTemplate={`(${notifyCount}) %s - Bangumi 番组计划`}```？

2023-04-03 07:16 UTC, FoundTheWOUT commented
有新通知肯定是没问题的，主要问题是进去其它页面时会被其它的 Helmet 覆盖掉

2023-04-03 07:18 UTC, y-young commented
> 有新通知肯定是没问题的，主要问题是进去其它页面时会被其它的 Helmet 覆盖掉

设置了 titleTemplate 其他页面的标题也会应用这个 template 吧，这样就不会被覆盖了

2023-04-03 07:32 UTC, FoundTheWOUT commented
没反应🤣，要不你试下？你应该可以直接推这个分支的

2023-04-03 07:36 UTC, trim21 commented
> > 其实现在也可以吧，测试下来没啥问题。（在 Header 里使用 useNotify 没有冲突问题，原因在注释里已经写了） 刚刚用 Mutation 试着实现了一次，不太行，用 Mutation 会出现循环调用，因为 mutate 的对象就是 observe 的对象。也可能是我不太会写（ 在每个 Helmet 上加个参数感觉也比较繁琐，如果是这样的话可能自定义个 Helmet 更好。 我觉得现在不去动 Helmet 也能解决就挺好的……
> 
> 试试在 Header 里放一个 Helmet，如果有新通知就设置属性 `` titleTemplate={`(${notifyCount}) %s - Bangumi 番组计划`} ``？

这个template不太对吧

2023-04-03 07:52 UTC, y-young commented
> 没反应🤣，要不你试下？你应该可以直接推这个分支的

确实，我又搞不懂这个库了……

用这个也行：
```js
      <Helmet
        onChangeClientState={() => {
          document.title = `(${noticeCount})...${document.title}`;
        }}
      />
```

2023-04-03 13:35 UTC, trim21 commented
```ts
      <Helmet
        onChangeClientState={() => {
          const prefix = noticeCount ? `(${noticeCount}) ` : ""
          document.title = `${prefix}${document.title}`;
        }}
      />
```

2023-04-03 14:24 UTC, trim21 requested changes
![image](https://user-images.githubusercontent.com/13553903/229538927-370ce83a-6d92-4520-9345-9dee8ba3bd6b.png)

2023-04-03 14:42 UTC, FoundTheWOUT commented
这次应该没问题了（
不过有时候跳转页面会丢失信息，不知道为啥
迟点试试那个 onChangeClientState

2023-04-03 15:16 UTC, FoundTheWOUT commented
> 原本的 title 里面有 `...` 怎么办
> 
> https://bgm.tv/subject/349223 https://bgm.tv/subject/318004

吸~迟点再搞了（

2023-04-03 15:31 UTC, trim21 commented on packages/website/src/components/Helmet.tsx
> +  const { noticeCount } = useNotify() ?? { noticeCount: 0 };
`useNotify()` 在没有provider的情况下是 null，所以会导致一些测试出错。

不过我感觉这里也不用具体给每个失败的测试都加上provider，就直接加了个fallback。

2023-04-03 15:44 UTC, y-young commented
要不要用一些类似 https://jotai.org/ 的全局状态管理工具？不然 Context 越加越多

2023-04-03 15:46 UTC, trim21 commented on packages/website/src/hooks/use-notify.tsx
> +  return React.useContext(NoticeContext) ?? { noticeCount: 0 };
`React.useContext(NoticeContext)` 在没有provider的情况下是 null，所以会导致一些测试出错。

不过我感觉这里也不用具体给每个失败的测试都加上provider，就直接加了个fallback。

2023-04-03 15:47 UTC, trim21 commented
> 要不要用一些类似 https://jotai.org/ 的全局状态管理工具？不然 Context 越加越多

问问 @bangumi/frontend-collaborators

2023-04-03 16:06 UTC, y-young commented on packages/website/src/pages/index/notifications/index.tsx
> +    return <div>PLEASE LOGIN FIRST</div>;
之前错误页面已经做好了这里就直接抛个 Error 吧，然后错误信息也要人性化一点

2023-04-03 16:06 UTC, y-young commented on packages/website/src/shared/notifications.ts
> +interface setting {
这里改成大写就不需要考虑变量冲突加下划线了？

2023-04-03 16:06 UTC, y-young commented on packages/website/src/shared/notifications.ts
> +  '7': {
奇怪，上面的 key 都没有引号，是 formatter 没生效？

2023-04-03 16:08 UTC, trim21 commented on packages/website/src/components/Helmet.tsx
> +import { useNotify } from '@bangumi/website/hooks/use-notify.tsx';
ts5.0开始可以加扩展名了，而且用了打包器不是直接在runtime运行的，扩展名无所谓

2023-04-03 16:09 UTC, trim21 commented on packages/website/src/shared/notifications.ts
> +  '7': {
不是，formatter不会修改key的类型，这里一开始就是这么写的。

2023-04-03 16:13 UTC, y-young commented on packages/website/src/shared/notifications.ts
> +  '7': {
JS object 的 Key 都是 String 吧，写法上可以不加引号，看上去更简洁一些：https://mathiasbynens.be/notes/javascript-properties

2023-04-03 16:17 UTC, trim21 commented on packages/website/src/shared/notifications.ts
> +  '7': {
额，我是说prettier针对key quote的选项设置的是preserve（

2023-04-03 16:20 UTC, trim21 commented on packages/website/src/shared/notifications.ts
> +  '7': {
仔细看了下好像还真是formatter的特殊处理

2023-04-03 16:36 UTC, trim21 commented
发现一个问题，在首页 https://pr-473-sites--bangumi-next.netlify.app/ 的时候不会显示通知数量，但是在小组页面则显示了通知数量。

https://pr-473-sites--bangumi-next.netlify.app/group/sandbox

2023-04-03 16:40 UTC, y-young commented
> 发现一个问题，在首页 https://pr-473-sites--bangumi-next.netlify.app/ 的时候不会显示通知数量，但是在小组页面则显示了通知数量。
> 
> https://pr-473-sites--bangumi-next.netlify.app/group/sandbox
> 
> 不知道首页的Helmet应该加在什么地方？

首页还没做吧，所以没地方加（

2023-04-03 16:44 UTC, trim21 commented
那首页的留到后面再解决吧

2023-04-03 17:05 UTC, trim21 approved these changes
功能ok

2023-04-04 03:23 UTC, Ayase-252 commented on packages/website/src/components/Header/index.tsx
> +                  [style.iconNotificationNotice!]: noticeCount > 0,
css module 还需要 non-null assertion?

2023-04-04 03:26 UTC, FoundTheWOUT commented on packages/website/src/components/Header/index.tsx
> +                  [style.iconNotificationNotice!]: noticeCount > 0,
dts 感知不到 import 的 style 的类型（只知道是字符串或者 undefined，然后 undefined 作为 key 有类型报错），估计得配置一些什么才行

2023-04-04 03:26 UTC, FoundTheWOUT commented
> 首页还没做吧，所以没地方加（

加在 GroupLayout 里？

2023-04-04 03:56 UTC, trim21 commented on packages/website/src/components/Header/index.tsx
> +                  [style.iconNotificationNotice!]: noticeCount > 0,
ts5.0可以给任意文件写dts了

2023-04-04 03:59 UTC, FoundTheWOUT commented on packages/website/src/components/Header/index.tsx
> +                  [style.iconNotificationNotice!]: noticeCount > 0,
知道这个，上周看过ts5的 announcement，确实有提到css的dts，但不知道通过什么方式去实现。

2023-04-04 04:00 UTC, trim21 commented on packages/website/src/components/Header/index.tsx
> +                  [style.iconNotificationNotice!]: noticeCount > 0,
针对每个文件都写一遍也是有点太麻烦了

2023-04-04 04:07 UTC, trim21 commented on packages/website/src/components/Header/index.tsx
> +                  [style.iconNotificationNotice!]: noticeCount > 0,
好像有类似的工具，不知道麻烦不麻烦。

https://github.com/Quramy/typed-css-modules

2023-04-04 04:09 UTC, trim21 commented on packages/website/src/components/Header/index.tsx
> +                  [style.iconNotificationNotice!]: noticeCount > 0,
https://www.npmjs.com/package/vite-plugin-typed-css-modules

2023-04-04 04:22 UTC, trim21 commented
> > 首页还没做吧，所以没地方加（
> 
> 加在 GlobalLayout 里？

后面做首页的时候再说吧

2023-04-04 04:23 UTC, trim21 commented on packages/website/src/components/Header/index.tsx
> +                  [style.iconNotificationNotice!]: noticeCount > 0,
这个pr先这样吧。后面再考虑加上这个？

2023-04-05 05:11 UTC, merged