refactor: align GroupInfo component with design
bangumi/frontend pull request #511
Opened 2023-03-28 12:57 UTC by y-young

- 按钮文字及样式调整：
<img width="207" alt="image" src="https://user-images.githubusercontent.com/17172063/228242586-02b9f773-ea0c-4a07-a680-dbbb1ae7f3ce.png">

- 小组功能两个按钮封装为组件
- 删除发表新话题页的右边栏
- 删除小组信息 Section title
- 删除帖子页的小组功能板块
- Layout 右边栏宽度调整

2023-03-29 08:20 UTC, FoundTheWOUT commented on packages/website/src/pages/index/group/components/GroupActions.tsx
> +    return null;
总觉得组件自己控制自己显不显示有点怪😂，上次用那个分页组件也是，调了半天，最后发现是组件内部返回 null 了（

2023-03-29 08:34 UTC, y-young commented on packages/website/src/pages/index/group/components/GroupActions.tsx
> +    return null;
是有点（
然而到处写 useUser 和 `user && ` 也挺烦的

2023-03-30 03:42 UTC, Ayase-252 commented on packages/website/src/pages/index/group/components/GroupActions.tsx
> +      <Button size={size} color='blue' type='secondary'>
现在是没实现功能吗？TODO 下，然后 disable 下吗？

2023-03-30 04:48 UTC, trim21 requested changes

2023-03-30 04:48 UTC, trim21 commented on packages/website/src/pages/index/group/components/GroupActions.tsx
> +      {/* TODO */}
加上TODO的具体描述

2023-03-30 07:26 UTC, trim21 commented
ok

2023-04-03 03:53 UTC, FoundTheWOUT approved these changes

2023-04-03 06:11 UTC, trim21 approved these changes

2023-04-03 06:14 UTC, merged