feat: wiki upload-img
bangumi/frontend pull request #542
Opened 2023-04-11 09:15 UTC by Jan30chen

wiki页面的上传封面页面，可以在这个条目`/subject/184017/wiki/upload_img`看看效果
虽然功能都实现了，不过估计代码瑕疵的地方还有很多，大佬们帮忙看看有什么要修改或者遗漏的地方
这个页面需要写jest的测试文件吗？

2023-04-11 09:20 UTC, trim21 commented
res是可以根据status code进行type narrow的

2023-04-11 09:25 UTC, Jan30chen commented
> res是可以根据status code进行type narrow的

具体可以参考那部分代码吗？

2023-04-11 09:27 UTC, Jan30chen commented
哎呀，寄了，看了一下是请求的错误处理那部分orz

2023-04-11 10:30 UTC, trim21 commented
> > res是可以根据status code进行type narrow的
> 
> 具体可以参考哪一部分的代码吗？

`oazClent.$method` 的返回值

2023-04-11 10:40 UTC, trim21 commented
400和401响应应该检查一下error code然后发一个toast的

2023-04-16 02:47 UTC, FoundTheWOUT commented on packages/website/src/pages/index/subject/[id]/wiki/upload_img.tsx
> +      }
这里是不是可以用三元表达式

2023-04-16 13:28 UTC, Jan30chen commented on packages/website/src/pages/index/subject/[id]/wiki/upload_img.tsx
> +      }
> 这里是不是可以用三元表达式

之前写到这里对await和三元在一起的写法不是很有把握，不知道是`A ? await B : await C`还是`A ? await B : C`，说先用`if`写着先，之后查查再改，然后忘记了

2023-04-17 09:06 UTC, Jan30chen commented
> 400和401响应应该检查一下error code然后发一个toast的

看`client.ts`里面，接口非200接口返回的`data`就是一个Error对象，那我把`res.data`直接往外抛，然后去`toast(error.message)`成不成啊。400和401的响应处理，是说根据`code`判断不同的错误情形，译成中文去`toast`的意思吗？

2023-04-17 16:12 UTC, trim21 commented
> > 400和401响应应该检查一下error code然后发一个toast的
> 
> 看`client.ts`里面，接口非200接口返回的`data`就是一个Error对象，那我把`res.data`直接往外抛，然后去`toast(error.message)`成不成啊。400和401的响应处理，是说根据`code`判断不同的错误情形，译成中文去`toast`的意思吗？

这里的error不是js的error，只是一个object而已。

2023-04-17 16:13 UTC, trim21 commented
感觉应该重命名一下这个类型以避免误会

2023-04-17 16:57 UTC, trim21 commented
> 400和401的响应处理，是说根据`code`判断不同的错误情形，译成中文去`toast`的意思吗？

对的

2023-04-19 06:54 UTC, trim21 commented on packages/website/src/pages/index/subject/[id]/wiki/upload_img.tsx
> +        throw new Error(err.message, { cause: err });
这里干嘛还要throw啊，直接toast不就好了吗。这里只catch网络错误就好了

2023-04-19 07:33 UTC, Jan30chen commented on packages/website/src/pages/index/subject/[id]/wiki/upload_img.tsx
> +        throw new Error(err.message, { cause: err });
> 这里干嘛还要throw啊，直接toast不就好了吗。这里只catch网络错误就好了

我理解响应体有误，这边和上面的逻辑确实不对，我再改一下

2023-04-19 08:46 UTC, Jan30chen commented on packages/website/src/pages/index/subject/[id]/wiki/upload_img.tsx
> +        throw new Error(err.message, { cause: err });
> 这里干嘛还要throw啊，直接toast不就好了吗。这里只catch网络错误就好了

又改了一下，瞅瞅行不行，感觉我把自己绕进去了；
上传封面报400的时候，原先的写法是直接进到`catch`语句里面去了，判断不了`code`，我就直接把这边的`try…catch`块去掉了；下面投票这个接口我就直接用`try…catch`块去`toast`了；
另外，我测了一下上传错误格式，接口返回的`code`并不是`"IMAGE_FORMAT_NOT_SUPPORT"`
```
{"code":"BAD_REQUEST","error":"Bad Request","message":"not valid image, only support jpeg, jpg, png, webp","statusCode":400}

2023-04-19 08:50 UTC, Jan30chen commented
这个构建失败的问题又是啥原因啊，看报错看不出啥门道 @Ayase-252

2023-04-19 18:53 UTC, trim21 commented on packages/website/src/pages/index/subject/[id]/wiki/upload_img.tsx
> +      if (res.status === 200) {
这里的错误处理还是不对啊，在`res.status !== 200`的情况下是不会throw的

2023-04-19 18:56 UTC, trim21 commented on packages/website/src/pages/index/subject/[id]/wiki/upload_img.tsx
> +        throw new Error(err.message, { cause: err });
这里有两个可能的错误需要处理，一个是fetch失败抛出来的`Error`，另一个是fetch成功，但是返回的响应不是200。

我修一下这个error code

2023-04-20 02:16 UTC, Jan30chen commented on packages/website/src/pages/index/subject/[id]/wiki/upload_img.tsx
> +            {covers.map((cover: CoverType) => {
> 类型问题，你的本地 IDE 没有报错吗😂。不过这里为什么要再定义一个 CoverType，应该是有类型的啊

我的IDE提示我这个`map`函数里的`cover`是any类型，我才照着响应数据的格式补了个`CoverType`上去的，反而出问题了吗。那这边咋改才行？<(＿　＿)>

2023-04-20 02:21 UTC, trim21 commented on packages/website/src/pages/index/subject/[id]/wiki/upload_img.tsx
> +            {covers.map((cover: CoverType) => {
两个问题
1. 你 `CoverType` 写错了，`voted` 是 `boolean` 而不是 `true`
2. 这里我试了一下是TypeScript可以正常推导出covers和cover的类型的，应该不需要手动再写一遍

2023-04-20 02:24 UTC, Jan30chen commented on packages/website/src/pages/index/subject/[id]/wiki/upload_img.tsx
> +        throw new Error(err.message, { cause: err });
> 这里有两个可能的错误需要处理，一个是fetch在http请求失败失败而抛出来的 js `Error`，另一个是fetch成功，但是返回的响应不是200，需要根据res.status和res.data.code进行处理。
> 
> 我修一下这个error code

行，我再改动一下；我以为这两种错误都会到`catch`语句里去

2023-04-20 02:50 UTC, Jan30chen commented on packages/website/src/pages/index/subject/[id]/wiki/upload_img.tsx
> +      if (res.status === 200) {
所以还是要加个`else`块把错误抛出去吗

2023-04-20 02:57 UTC, trim21 commented on packages/website/src/pages/index/subject/[id]/wiki/upload_img.tsx
> +      if (res.status === 200) {
> 所以还是要加个`else`块把错误抛出去吗

直接toast具体的错误，类似下面的`uploadSubjectCover`那样。

2023-04-20 02:58 UTC, trim21 commented on packages/website/src/pages/index/subject/[id]/wiki/upload_img.tsx
> +      if (res.status === 200) {
> > 所以还是要加个`else`块把错误抛出去吗
> 
> 直接toast具体的错误，类似下面的`uploadSubjectCover`那样。

我没理解错的话这里跟下面的`uploadSubjectCover`实际上没什么大区别吧 🤔

2023-04-20 03:01 UTC, Jan30chen commented on packages/website/src/pages/index/subject/[id]/wiki/upload_img.tsx
> +            {covers.map((cover: CoverType) => {
> 两个问题
> 
> 1. 你 `CoverType` 写错了，`voted` 是 `boolean` 而不是 `true`
> 2. 这里我试了一下是TypeScript可以正常推导出covers和cover的类型的，应该不需要手动再写一遍

嗐，又犯低级错误了我orz，那我直接把CoverType删掉好了，我这边IDE的报错就不管了

2023-04-20 03:04 UTC, trim21 commented on packages/website/src/pages/index/subject/[id]/wiki/upload_img.tsx
> +            {covers.map((cover: CoverType) => {
> > 两个问题
> > 
> > 1. 你 `CoverType` 写错了，`voted` 是 `boolean` 而不是 `true`
> > 2. 这里我试了一下是TypeScript可以正常推导出covers和cover的类型的，应该不需要手动再写一遍
> 
> 嗐，又犯低级错误了我orz，那我直接把CoverType删掉好了，我这边IDE的报错就不管了

我试了一下无论是webstorm还是vscode都是能正常推导的，你用的什么？

2023-04-20 03:31 UTC, Ayase-252 commented on packages/website/src/pages/index/subject/[id]/wiki/upload_img.tsx
> +    const uploader = document.getElementById('coverUploader');
拿 ref 就行了吧，react 里避免直接操作 dom。

2023-04-20 11:51 UTC, trim21 commented on packages/website/src/pages/index/subject/[id]/wiki/upload_img.tsx
> +            <Image src={(current as CurrentType).thumbnail} />
这里不太对吧... 没上传过封面的条目 `current === undefined` 的

2023-04-21 03:04 UTC, Jan30chen commented on packages/website/src/pages/index/subject/[id]/wiki/upload_img.tsx
> +            {covers.map((cover: CoverType) => {
> > > 两个问题
> > > 
> > > 1. 你 `CoverType` 写错了，`voted` 是 `boolean` 而不是 `true`
> > > 2. 这里我试了一下是TypeScript可以正常推导出covers和cover的类型的，应该不需要手动再写一遍
> > 
> > 
> > 嗐，又犯低级错误了我orz，那我直接把CoverType删掉好了，我这边IDE的报错就不管了
> 
> 我试了一下无论是webstorm还是vscode都是能正常推导的，你用的什么？

VScode
```
版本: 1.70.0 (user setup)
提交: da76f93349a72022ca4670c1b84860304616aaa2
日期: 2022-08-04T04:38:16.462Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.19043
```
![](https://p.sda1.dev/11/c87c3110b2899420ae0ebe9c5843949c/sp20230421_110123_226.png)

2023-04-21 03:11 UTC, Jan30chen commented on packages/website/src/pages/index/subject/[id]/wiki/upload_img.tsx
> +            <Image src={(current as CurrentType).thumbnail} />
> 这里不太对吧... 没上传过封面的条目 `current === undefined` 的

是的是的，我加一下判断……

2023-04-21 03:38 UTC, Ayase-252 commented on packages/website/src/pages/index/subject/[id]/wiki/upload_img.tsx
文件命名不是带下划线的吧，可以比照其他组件改下？

2023-04-21 04:05 UTC, cokemine commented on packages/website/src/pages/index/subject/[id]/wiki/upload_img.tsx
> +            {covers.map((cover: CoverType) => {
useSWR返回的data也没有类型吗？更新一下vscode试试

2023-04-21 04:14 UTC, trim21 commented on packages/website/src/pages/index/subject/[id]/wiki/upload_img.tsx
> +            {covers.map((cover: CoverType) => {
为啥会这样。。。 我记得 ts 不需要装扩展吧 设置一下 `typescript.tsdk` 试试？

2023-04-21 05:29 UTC, Jan30chen commented on packages/website/src/pages/index/subject/[id]/wiki/upload_img.tsx
> 文件命名不是带下划线的吧，可以比照其他组件改下？

所以是大驼峰的写法吗？加下划线是因为我看`/wiki`里有个`edit_detail.tsx`文件

2023-04-21 05:34 UTC, Jan30chen commented on packages/website/src/pages/index/subject/[id]/wiki/upload_img.tsx
> +            {covers.map((cover: CoverType) => {
VScode 现在是自动更新的模式，应该是最新版
说起来，某一次拉上游的master代码后，我每个文件的引用部分就一直报错，不知道和这个有没有关系？
![image](https://user-images.githubusercontent.com/36024707/233548624-656b14d5-4770-49fd-be19-53ba427e4936.png)
![image](https://user-images.githubusercontent.com/36024707/233548630-7277221f-3c12-463d-84bb-28b4be6bcad9.png)

2023-04-21 06:18 UTC, Ayase-252 commented on packages/website/src/pages/index/subject/[id]/wiki/upload_img.tsx
哦不对，这个和页面 url 有关，没事了

2023-04-21 07:06 UTC, cokemine commented on packages/website/src/pages/index/subject/[id]/wiki/upload_img.tsx
> +            {covers.map((cover: CoverType) => {
现在最新版本是
版本: 1.77.3
提交: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710
日期: 2023-04-12T09:16:02.548Z (1 周前)

是不是没有重新装一下依赖 `pnpm install`。你现在的TS的版本应该不是5.0

2023-04-21 08:03 UTC, Jan30chen commented on packages/website/src/pages/index/subject/[id]/wiki/upload_img.tsx
> +            {covers.map((cover: CoverType) => {
> 现在最新版本是 版本: 1.77.3 提交: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710 日期: 2023-04-12T09:16:02.548Z (1 周前)
> 
> 是不是没有重新装一下依赖 `pnpm install`。你现在的TS的版本应该不是5.0

可以，ok了，我的vscode设置成自动更新不知为什么没作用，导致版本太低；
我跑去官网重新下载了最新版本，这些报错问题都解决了

2023-04-21 08:11 UTC, Jan30chen commented on packages/website/src/pages/index/subject/[id]/wiki/upload_img.tsx
> +            {covers.map((cover: CoverType) => {
> > 现在最新版本是 版本: 1.77.3 提交: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710 日期: 2023-04-12T09:16:02.548Z (1 周前)
> > 是不是没有重新装一下依赖 `pnpm install`。你现在的TS的版本应该不是5.0
> 
> 可以，ok了，我的vscode设置成自动更新不知为什么没作用，导致版本太低； 我跑去官网重新下载了最新版本，这些报错问题都解决了
---
下载了最新版本，结果两个版本并存在我电脑上了；我还以为我的vscode版本又被自动回退了……

2023-04-21 08:22 UTC, Jan30chen commented on packages/website/src/pages/index/subject/[id]/wiki/upload_img.tsx
> +    const uploader = document.getElementById('coverUploader');
我把操作input:file的value这语句直接删掉了，感觉也没必要重置上传组件的值，上传成功后会把`uploadContent`置空，“上传图片”按钮也就不可见了，不会出现重复上传的情况

2023-04-21 08:53 UTC, trim21 commented on packages/website/src/pages/index/subject/[id]/wiki/upload_img.tsx
> +          {current?.thumbnail && (
这里还有必要取属性吗

2023-04-21 08:55 UTC, cokemine commented
我这边点击 label 触发不到隐藏 input 的选择文件。
这个 useEffect 用法很奇怪，为什么不用React的onChange事件却在useEffect监听DOM的原生事件？

2023-04-21 10:12 UTC, trim21 commented on packages/website/src/pages/index/subject/[id]/wiki/upload_img.tsx
> +          {current?.thumbnail && (
```suggestion
          {current && (
```

2023-04-21 11:02 UTC, trim21 commented on packages/website/src/pages/index/subject/[id]/wiki/upload_img.tsx
> +        const code = reader?.result as string;
这里reader不会是null或者undefined吧，这个`?` 有作用吗？

2023-04-21 11:03 UTC, trim21 commented on packages/website/src/pages/index/subject/[id]/wiki/upload_img.tsx
> +        setUploadContent(code.replace(/^data:image\/\w+;base64,/, ''));
能不能直接slice，可读性高一点（）

2023-04-21 14:17 UTC, trim21 commented on packages/website/src/pages/index/subject/[id]/wiki/upload_img.tsx
> +        setUploadContent(code.replace(/^data:image\/\w+;base64,/, ''));
```suggestion
        setUploadContent(code.slice('data:text/plain;base64,'.length));
```

2023-04-21 14:18 UTC, trim21 commented on packages/website/src/pages/index/subject/[id]/wiki/upload_img.tsx
> +        const code = reader?.result as string;
```suggestion
        const code = reader.result as string;
```

2023-04-21 14:20 UTC, trim21 commented on packages/website/src/pages/index/subject/[id]/wiki/upload_img.tsx
> +    const readImage = () => {
这里能不能用Promise包成个async（

2023-04-24 07:10 UTC, Jan30chen commented on packages/website/src/pages/index/subject/[id]/wiki/upload_img.tsx
> +        setUploadContent(code.replace(/^data:image\/\w+;base64,/, ''));
> 

这个前缀因为图片的类型不同可能长度不同，直接读`'data:text/plain;base64,'.length`长度会有问题吧

2023-04-24 07:16 UTC, trim21 commented on packages/website/src/pages/index/subject/[id]/wiki/upload_img.tsx
> +        setUploadContent(code.replace(/^data:image\/\w+;base64,/, ''));
哦豁，那还是你这个写法对

2023-04-26 11:49 UTC, Jan30chen commented
> 我这边点击 label 触发不到隐藏 input 的选择文件。 感觉可以改下 Button 组件复用一下 这个 useEffect 用法很奇怪，获取上传的图片为什么不用React的onChange事件却在useEffect监听DOM的原生事件？

是的是的，直接用onchange事件更简单，改正过了；选择不了文件是因为我把`input:file`的id删了，我以为`for`标签是去找`name`属性来着，也改掉了。
上传按钮这部分先列为在办吧（

2023-04-26 11:52 UTC, Jan30chen commented on packages/website/src/pages/index/subject/[id]/wiki/upload_img.tsx
> +    const readImage = () => {
> 这里能不能用Promise包成个async（
> 
> 比如这样
> 
> ```ts
>   async function uploadAsBase64(file) {
>     return new Promise((resolve, reject) => {
>       const reader = new FileReader();
> 
>       reader.onload = function () {
>         const content = reader.result;
>         resolve(content.slice('data:text/plain;base64,'.length));
>       };
> 
>       reader.onerror = function () {
>         reject(new Error('failed to read file'));
>         console.log('there are some problems');
>       };
> 
>       reader.readAsDataURL(file);
>     });
>   }
> ```

尝试着改了一下，把转换base64的部分拆出一个函数来了，你看看是不是这个意思。其实我不是很明白你的意思（

2023-04-26 11:57 UTC, Jan30chen commented
和UI讨论过了，没有封面上传的时候，就直接去掉前两行，只保留上传封面的部分了。
已上传的条目：`/subject/184017/wiki/upload_img`
还未上传过的条目：`/subject/363612/wiki/upload_img`
---
另外发现旧站还有一个点击封面展示大图的功能；这个悬浮图片展示模块，有现成的组件吗？
![image](https://user-images.githubusercontent.com/36024707/234567358-7287a5c4-95ed-4865-bc03-e50b3be1bdfb.png)

2023-04-26 12:02 UTC, Jan30chen commented
哦，还有就是上传一个700k的图片时，还是会有413请求体过大的问题

2023-04-26 13:19 UTC, cokemine commented on packages/website/src/pages/index/subject/[id]/wiki/upload_img.tsx
> +  };
readAsBase64 和 getShortName 这两个函数和组件状态没有关系，最好移到组件外面去否则每次渲染都会重新生成

2023-04-26 13:20 UTC, cokemine commented
> 另外发现旧站还有一个点击封面展示大图的功能；这个悬浮图片展示模块，有现成的组件吗？ 

没有吧，还没有设计感觉可以先放一放

2023-04-26 21:12 UTC, trim21 commented on packages/website/src/pages/index/subject/[id]/wiki/upload_img.tsx
> +          {Boolean(covers.length) && (
```suggestion
          {covers.length && (
```

2023-04-27 00:08 UTC, trim21 commented
> 哦，还有就是上传一个700k的图片时，还是会有413请求体过大的问题

好了，才发现这个检查有好几个...

2023-04-27 04:11 UTC, Ayase-252 commented on packages/website/src/pages/index/subject/[id]/wiki/upload_img.tsx
> +  const getShortName = (name: string): string => {
这个函数能注释下吗？一下子没看明白

2023-04-27 05:07 UTC, Jan30chen commented on packages/website/src/pages/index/subject/[id]/wiki/upload_img.tsx
> +  const getShortName = (name: string): string => {
> 这个函数能注释下吗？一下子没看明白

如果文件名很长，展示在dom上太长我觉得会影响这部分观感；这个函数就是对太长的文件名（目前是超过50长度），截取前面与后面，省略中间。我加个注释好了。

2023-04-27 11:44 UTC, trim21 commented on packages/website/src/pages/index/subject/[id]/wiki/upload_img.tsx
> +  const getShortName = (name: string): string => {
函数注释用tsdoc或者jsdoc吧，这样的注释vscode没法提取

2023-04-27 11:48 UTC, trim21 commented on packages/website/src/pages/index/subject/[id]/wiki/upload_img.tsx
> +  const getShortName = (name: string): string => {
![image](https://user-images.githubusercontent.com/13553903/234852813-675e3ac8-c83b-4155-8be8-dcc3f5a07b43.png)
![image](https://user-images.githubusercontent.com/13553903/234852878-a2acda8a-d242-41f1-ab4d-2a733f73e21e.png)

![image](https://user-images.githubusercontent.com/13553903/234852955-5838ab10-948a-47f1-8fd5-8bb01f23c5d8.png)
![image](https://user-images.githubusercontent.com/13553903/234852994-b140ce5e-a397-4acd-a242-fd1f57657a94.png)

2023-04-27 11:49 UTC, Ayase-252 commented on packages/website/src/pages/index/subject/[id]/wiki/upload_img.tsx
> +  const fore = name.slice(0, Math.floor((max * 3) / 5));
这个 * 3 / 5 是啥操作。。。

2023-04-27 12:07 UTC, trim21 commented
显示效果好像挺ok的

2023-04-27 12:08 UTC, trim21 commented on packages/website/src/pages/index/subject/[id]/wiki/upload_img.tsx
> +  if (!name || name.length <= max) {
文件名字符串可能为空吗...

2023-04-27 12:11 UTC, trim21 commented on packages/website/src/pages/index/subject/[id]/wiki/upload_img.tsx
> +    reader.onerror = () => {
```suggestion
    reader.onerror = (err: unknown) => {
```

这里应该是有个error入参的

2023-04-27 12:12 UTC, trim21 commented on packages/website/src/pages/index/subject/[id]/wiki/upload_img.tsx
> +      if (err instanceof Error) {
不是Error实例也应该处理的

2023-04-27 12:16 UTC, trim21 commented on packages/website/src/pages/index/subject/[id]/wiki/upload_img.tsx
> +  const fore = name.slice(0, Math.floor((max * 3) / 5));
这里应该直接取固定长度吧？扩展名`.ext`应该要全部显示，然后按照长度省略中间的

2023-04-29 12:55 UTC, trim21 commented on packages/website/src/pages/index/subject/[id]/wiki/upload_img.tsx
> + * @param {File} img
有ts就不用加type了

2023-04-29 12:56 UTC, trim21 commented on packages/website/src/pages/index/subject/[id]/wiki/upload_img.tsx
> + * @param {File} img
`@description` 好像也不用加，不过加了也没啥问题…

2023-04-29 13:08 UTC, Jan30chen commented
怎么回复一下就多一个`Pending`的回复层，我这是开了啥奇怪的开关吗

2023-04-29 13:09 UTC, trim21 commented
> 怎么回复一下就多一个`Pending`的回复层，我这是开了啥奇怪的开关吗

你用那个 add single comment 按钮回复的话就不会了，用`commit`按钮的话github的review设计是默认batch的

2023-04-29 13:37 UTC, trim21 commented on packages/website/src/pages/index/subject/[id]/wiki/upload_img.tsx
> + * @param {File} img
```suggestion
```

2023-04-29 13:37 UTC, trim21 commented on packages/website/src/pages/index/subject/[id]/wiki/upload_img.tsx
> + * @return {[String, String]} 图片名与base64字符串
```suggestion
 * @return 图片名与base64字符串
```

2023-04-29 13:37 UTC, trim21 commented on packages/website/src/pages/index/subject/[id]/wiki/upload_img.tsx
> +   * @param {Event} event
```suggestion
```

2023-04-29 13:41 UTC, trim21 commented on packages/website/src/pages/index/subject/[id]/wiki/upload_img.tsx
> +  const fore = name.slice(0, max);
文件名刚好50长度的话是不是会显示两遍扩展名？

2023-04-29 15:46 UTC, Jan30chen commented
> > 怎么回复一下就多一个`Pending`的回复层，我这是开了啥奇怪的开关吗
> 
> 你用那个 add single comment 按钮回复的话就不会了，用~ `comment ` ~ `start a review` 按钮的话github的review设计是默认batch的

我点进提交里，在代码上直接点“+”号，出来的这个评论栏就只有一个“Add review comment”的按钮；是点错地方了吗
![image](https://user-images.githubusercontent.com/36024707/235311310-36992f59-f2f9-4287-bc22-1f8a948448ce.png)

2023-04-29 15:49 UTC, trim21 commented
![image](https://user-images.githubusercontent.com/13553903/235311518-f4445ce1-b9f6-432c-b23b-51b67f039d79.png)

2023-04-29 15:52 UTC, Jan30chen commented
> ![image](https://user-images.githubusercontent.com/13553903/235311518-f4445ce1-b9f6-432c-b23b-51b67f039d79.png)

哦哦，这是要点完成review是吗

2023-04-29 15:54 UTC, trim21 commented
怎么close了，你是点错了吗...

你回复的时候可以直接用这个 add single comment

![image](https://user-images.githubusercontent.com/13553903/235311700-d54fce0a-8962-4de4-8df7-efb69560f663.png)

2023-04-29 15:57 UTC, Jan30chen commented
> 怎么close了，你是点错了吗...
> 
> 你回复的时候可以直接用这个 add single comment
> 
> ![image](https://user-images.githubusercontent.com/13553903/235311700-d54fce0a-8962-4de4-8df7-efb69560f663.png)

确实，手滑了，找半天reopen按钮；我这github的知识还是得恶补一下啊orz
这个review框是从哪儿点开的，感觉我的界面好像不太一样，难道是因为我是提交人吗

2023-04-29 15:58 UTC, trim21 commented
![image](https://user-images.githubusercontent.com/13553903/235311874-bfce05c5-5a68-4c5d-ada7-dc44d10e8778.png)

2023-04-29 16:02 UTC, trim21 commented
> @description 好像也不用加，不过加了也没啥问题…

> 用了个自动加函数头部注释的插件，默认是这样的；
@param行不需要，@return行还要不要呢

这里 `@param` 行没有任何有效信息就没必要了... `@return` 还是有的

2023-04-29 16:03 UTC, Jan30chen commented on packages/website/src/pages/index/subject/[id]/wiki/upload_img.tsx
> +  const fore = arr[0]!; // 文件名
本来只是想简单转换一下，结果这边越写越麻烦了，不知道有没有更好的办法；
其实还是有极端情况没法处理，比如带特殊符号的后缀，特别长的后缀啥的，这种还是不考虑了吧。
明天起来再瞅瞅，现在摆了（

2023-04-29 16:04 UTC, Jan30chen commented
> ![image](https://user-images.githubusercontent.com/13553903/235311874-bfce05c5-5a68-4c5d-ada7-dc44d10e8778.png)
> 
> 鼠标放上去会有一个蓝色的加号

之前也是点的这里，界面不太一样；不过我把上面开着的review去finish之后，就变回来了

2023-04-29 16:04 UTC, trim21 commented on packages/website/src/pages/index/subject/[id]/wiki/upload_img.tsx
> +  const fore = arr[0]!; // 文件名
你可以直接前面slice35后面slice10，中间加省略号，不会有超过10个字符长度的扩展名了吧...

2023-04-29 16:11 UTC, trim21 commented
> > ![image](https://user-images.githubusercontent.com/13553903/235311874-bfce05c5-5a68-4c5d-ada7-dc44d10e8778.png)
> > 鼠标放上去会有一个蓝色的加号
> 
> 之前也是点的这里，界面不太一样；不过我把上面开着的review去finish之后，就变回来了

我这个图就是在自己的pr里面截的，没有pending review的情况

2023-05-01 04:57 UTC, trim21 approved these changes

2023-05-01 14:20 UTC, cokemine commented on packages/website/src/pages/index/subject/[id]/wiki/upload_img.tsx
> +        userMsg ? toast(userMsg, { type: 'error' }) : toast(res.data.message, { type: 'error' });
```suggestion
        toast(userMsg ?? res.data.message, { type: 'error' });
```

2023-05-01 14:23 UTC, cokemine commented
目前得票最高的封面图片没有显示 by xxx，可以直接服用WikiCoverItem这个组件，不显示投票什么的。

目前得票最高的封面图片、已上传的封面图片还有选择图片这三栏的间距应该是40px，现在是20px

2023-05-02 06:47 UTC, Jan30chen commented on packages/website/src/pages/index/subject/[id]/wiki/upload_img.tsx
> +        userMsg ? toast(userMsg, { type: 'error' }) : toast(res.data.message, { type: 'error' });
> 

我点这个“commit suggestion”按钮，是不是就相当于直接提交这个修改到分支上了
![image](https://user-images.githubusercontent.com/36024707/235598362-dcc716b0-1a3a-446c-97b6-b6eeb0322d98.png)

2023-05-02 06:53 UTC, Jan30chen commented
> 目前得票最高的封面图片没有显示 by xxx，可以直接复用WikiCoverItem这个组件，不显示投票什么的。
> 
> 目前得票最高的封面图片、已上传的封面图片还有选择图片这三栏的间距应该是40px，现在是20px
> 
> 别的没啥问题

设计图第一行应该是有改动了，之前这边记得是20px，没有这个by行；
接口目前的`current`也只返回了图片路径，没有`creator`属性，得多加返回属性了 @trim21

2023-05-02 07:04 UTC, cokemine commented on packages/website/src/pages/index/subject/[id]/wiki/upload_img.tsx
> +        userMsg ? toast(userMsg, { type: 'error' }) : toast(res.data.message, { type: 'error' });
对的

2023-05-02 07:10 UTC, trim21 commented
> > 目前得票最高的封面图片没有显示 by xxx，可以直接复用WikiCoverItem这个组件，不显示投票什么的。
> > 目前得票最高的封面图片、已上传的封面图片还有选择图片这三栏的间距应该是40px，现在是20px
> > 别的没啥问题
> 
> 设计图第一行应该是有改动了，之前这边记得是20px，没有这个by行； 接口目前的`current`也只返回了图片路径，没有`creator`属性，得多加返回属性了 @trim21

不是已经返回了全部封面的信息吗？从里面找不就行了。。。

2023-05-02 07:15 UTC, Jan30chen commented
> > > 目前得票最高的封面图片没有显示 by xxx，可以直接复用WikiCoverItem这个组件，不显示投票什么的。
> > > 目前得票最高的封面图片、已上传的封面图片还有选择图片这三栏的间距应该是40px，现在是20px
> > > 别的没啥问题
> > 
> > 
> > 设计图第一行应该是有改动了，之前这边记得是20px，没有这个by行； 接口目前的`current`也只返回了图片路径，没有`creator`属性，得多加返回属性了 @trim21
> 
> 不是已经返回了全部封面的信息吗？从里面找不就行了。。。

用`current`的`raw`属性去`covers`里面找吗，会不会有点绕

2023-05-02 08:03 UTC, trim21 commented
有道理，我看看返回一个ID吧

2023-05-02 15:30 UTC, trim21 requested changes

2023-05-02 15:30 UTC, trim21 commented on packages/website/src/pages/index/subject/[id]/wiki/upload_img.tsx
> +        onCommentUpdate!();
如果这里是 optional 的就不要用 `!` 了，用 `?.`

2023-05-04 08:40 UTC, cokemine commented on packages/website/src/pages/index/subject/[id]/wiki/upload_img.tsx
> +        userMsg ? toast(userMsg, { type: 'error' }) : toast(res.data.message, { type: 'error' });
这里又改回来了....还有距离还是20px没改成40px

2023-05-06 09:33 UTC, Jan30chen commented on packages/website/src/pages/index/subject/[id]/wiki/upload_img.tsx
> +        userMsg ? toast(userMsg, { type: 'error' }) : toast(res.data.message, { type: 'error' });
> 这里又改回来了....还有距离还是20px没改成40px

不知怎么覆盖掉了，我还原一下；
20px的间距是说哪里，我看这边都是40px
![image](https://user-images.githubusercontent.com/36024707/236616006-b532d927-dbeb-4439-b250-8392b0861523.png)
![image](https://user-images.githubusercontent.com/36024707/236616016-f4368b4b-6d08-4938-8e06-4ba12ba10aaa.png)

2023-05-06 12:57 UTC, cokemine commented on packages/website/src/pages/index/subject/[id]/wiki/upload_img.tsx
> +        userMsg ? toast(userMsg, { type: 'error' }) : toast(res.data.message, { type: 'error' });
看错了，这里没问题了(bgm38)

2023-05-06 12:58 UTC, cokemine approved these changes

2023-05-06 13:06 UTC, trim21 approved these changes

2023-05-06 13:08 UTC, merged